title: BenchAMRking<sup>&copy;</sup>
description: Species-specific pipelines for gold standard benchmarking of bacterial next generation sequencing (NGS) contigs to phenotype data.
show_buttons: false

collections:
  - workflows
