title: AMR-Pathfinder
trademark: AMR-Pathfinder<sup>&copy;</sup>
description: A simple, scalable, secure Galaxy web application for benchmarking antimicrobial resistance gene prediction.
show_buttons: false

collections:
  - workflows
