title: BenchAMRking
trademark: BenchAMRking<sup>&copy;</sup>
description: A simple user friendly, scalable, secure Galaxy web application for benchmarking antimicrobial resistance gene detection.
show_buttons: false

collections:
  - workflows
